# Generated by Django 3.2.7 on 2021-11-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='username',
        ),
    ]
